"use client";

import { ArrowRight, CheckCircle2, Clock3, Mail, ShieldCheck, Wrench } from "lucide-react";
import Link from "next/link";
import { useEffect, useState } from "react";
import { apiRequest, getApiBase } from "@/lib/api";

type MaintenanceEntry = { name?: string; title?: string; body?: string; image?: string; status?: string; data?: Record<string, unknown> };
const defaults = {
  heroTitle: "Professional Care. Maximum Flight Time. Guaranteed Performance.",
  heroBody: "Expert drone maintenance and repairs for enterprise fleets, government & corporate operations.",
  introTitle: "Protect Your Fleet, Maximize Uptime, and Guarantee Compliance",
  introBody: "Your drone fleet is a high-value asset. From routine preventive maintenance to repairs, our technicians care for every airframe, battery and payload with precision.",
  packages: [
    { name: "Basic Maintenance", price: "From ৳7,500", accent: "blue", body: "Routine inspection and annual checkups.", features: ["Deep cleaning", "Flight and safety inspection", "Firmware update", "Maintenance report"] },
    { name: "Standard Maintenance", price: "From ৳14,500", accent: "blue", body: "For active fleets and frequent missions.", features: ["All Basic services", "Worn component assessment", "Battery health check", "Payload calibration"] },
    { name: "Premium Maintenance", price: "From ৳24,500", accent: "red", body: "For high-demand, mission-critical operations.", features: ["All Standard services", "Motor and electronics assessment", "Battery capacity certification", "Weather-seal inspection"] },
  ],
};
export default function MaintenancePage(){
  const [content,setContent]=useState(defaults); const [sent,setSent]=useState(""); const [error,setError]=useState("");
  useEffect(()=>{const load=async()=>{if(!getApiBase())return;try{const response=await apiRequest<{data?:MaintenanceEntry[]}>("/content/maintenance");const published=response.data||[];const find=(name:string)=>published.find(e=>(e.name||"").toLowerCase()===name);const hero=find("hero"),intro=find("intro");setContent(current=>({...current,heroTitle:hero?.title||current.heroTitle,heroBody:hero?.body||current.heroBody,introTitle:intro?.title||current.introTitle,introBody:intro?.body||current.introBody,packages:current.packages.map(item=>{const key=item.name.split(" ")[0].toLowerCase();const remote=find(key);const data=remote?.data||{};return remote?{...item,name:remote.title||item.name,body:remote.body||item.body,price:String(data.price||item.price),features:Array.isArray(data.features)?data.features.map(String):item.features}:item})}))}catch{/* keep defaults */}};void load()},[]);
  async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setError("");setSent("");if(!getApiBase()){setError("Backend API is not configured.");return;}const f=new FormData(e.currentTarget);try{const r=await apiRequest<{data?:{requestNumber?:string}}>("/maintenance-requests",{method:"POST",body:JSON.stringify({name:f.get("name"),phone:f.get("phone"),email:f.get("email"),serviceType:f.get("serviceType"),deviceModel:f.get("deviceModel"),preferredDate:f.get("preferredDate")||undefined,message:f.get("message")})});setSent(r.data?.requestNumber||"Submitted");e.currentTarget.reset()}catch(err){setError(err instanceof Error?err.message:"Unable to submit request")}}
  return <main className="maintenance-page"><section className="maintenance-hero"><div className="maintenance-hero-overlay"/><div className="page-container maintenance-hero-content"><p className="eyebrow">DRONE BANGLADESH MAINTENANCE</p><h1>{content.heroTitle}</h1><p>{content.heroBody}</p><div className="maintenance-proof"><span><ShieldCheck/> Certified technicians</span><span><Wrench/> Genuine parts</span><span><Clock3/> Fast turnaround</span><span><CheckCircle2/> Documented service</span></div><a href="#service-request" className="button button-red">Schedule service <ArrowRight size={16}/></a></div></section>
    <section className="page-container maintenance-content"><header className="maintenance-intro-heading"><h2>Drone Maintenance Services</h2><p>Call us: <a href="tel:+8801896123434">+880 1896-123434</a><i>|</i> Email: <a href="mailto:dronebangladesh567@gmail.com">dronebangladesh567@gmail.com</a></p></header><div className="maintenance-protect"><div className="maintenance-shield"><ShieldCheck size={72}/></div><div><h2>{content.introTitle}</h2><p>{content.introBody}</p></div></div>
    <section className="maintenance-packages"><h2>Maintenance Packages</h2><div className="package-grid">{content.packages.map(item=><article className={`package-card ${item.accent}`} key={item.name}><h3>{item.name}</h3><p>{item.body}</p><ul>{item.features.map(feature=><li key={feature}>{feature}</li>)}</ul><footer><strong>{item.price}</strong><a href="#service-request" className="button button-primary">Request service</a></footer></article>)}</div></section>
    <section id="service-request" className="maintenance-request-section"><div><h2>Request Maintenance</h2><p>Submit your drone details and our team will contact you.</p></div><form className="contact-form" onSubmit={submit}><div className="form-grid"><label>Name<input name="name" required/></label><label>Phone<input name="phone" required/></label></div><div className="form-grid"><label>Email<input name="email" type="email"/></label><label>Device model<input name="deviceModel"/></label></div><div className="form-grid"><label>Service type<select name="serviceType" required defaultValue="Routine Maintenance"><option>Routine Maintenance</option><option>Repair</option><option>Battery Service</option><option>Camera / Gimbal</option><option>Enterprise Fleet Service</option></select></label><label>Preferred date<input name="preferredDate" type="date"/></label></div><label>Message<textarea name="message" rows={4}/></label>{sent&&<p className="form-success">Request submitted. Reference: {sent}</p>}{error&&<p className="crud-error">{error}</p>}<button className="button button-red" type="submit">Submit request</button></form></section>
    <section className="maintenance-cta"><h2>Need help before booking?</h2><p>Talk to our support team about your aircraft or service issue.</p><Link href="/contact" className="button button-red">Contact us <ArrowRight size={16}/></Link><a href="mailto:dronebangladesh567@gmail.com"><Mail size={15}/> Email us</a></section></section></main>;
}
