"use client";

import { Download, ImagePlus, Link2, Pencil, Plus, Save, Search, Trash2, Upload, X } from "lucide-react";
import Link from "next/link";
import { useSearchParams } from "next/navigation";
import { useEffect, useMemo, useRef, useState } from "react";
import RichDescriptionEditor, { starterCss, starterHtml } from "@/components/rich-description-editor";
import { apiFormRequest, apiRequest, getApiBase } from "@/lib/api";

type ProductStatus = "published" | "draft" | "archived";
type MenuPlacement = { menu: "drones" | "handhelds" | "enterprise"; group: string; sortOrder: number; isActive: boolean };
type AdminProduct = {
  id: string; name: string; slug: string; brand: string; category: string; sku: string; price: number; oldPrice: number; stock: number; reorderLevel:number; unitCost:number; warehouse:string; supplier:string;
  images: string[]; image: string; status: ProductStatus; badge: string; youtubeUrl: string; description: string; descriptionHtml: string; descriptionCss: string; preorderEnabled: boolean; preorderDepositPercent: number; preorderNote: string;
  keyFeatures: string[]; specifications: Record<string,string>; isFeatured: boolean; isNewArrival: boolean; isPopular: boolean; isActive: boolean; menuPlacements: MenuPlacement[];
};
type ProductForm = Omit<AdminProduct,"id"|"specifications"|"keyFeatures"|"menuPlacements"> & {
  keyFeaturesText: string; specificationsText: string;
  dronesMenuGroup: string; dronesMenuOrder: number;
  handheldsMenuGroup: string; handheldsMenuOrder: number;
  enterpriseMenuGroup: string; enterpriseMenuOrder: number;
};
type ContentOption = { name?: string; title?: string };

const starterProduct: AdminProduct = { id:"demo-mini-5", name:"DJI Mini 5 Pro Fly More Combo Plus with RC2", slug:"dji-mini-5-pro-fly-more-combo-plus-rc2", brand:"DJI", category:"Camera Drone", sku:"DB-MINI5", price:117000, oldPrice:140000, stock:12, reorderLevel:5, unitCost:95000, warehouse:"Dhaka Main Warehouse", supplier:"", images:["/images/products/mini-5.jpg"], image:"/images/products/mini-5.jpg", status:"published", badge:"HOT", youtubeUrl:"", description:"A powerful ultra-light drone for creators.", descriptionHtml:starterHtml, descriptionCss:starterCss, preorderEnabled:true, preorderDepositPercent:30, preorderNote:"Reserve this product before the next shipment arrives.", keyFeatures:["Official product"], specifications:{Camera:"1-inch CMOS"}, isFeatured:true, isNewArrival:true, isPopular:true, isActive:true, menuPlacements:[] };
const blank: ProductForm = { name:"",slug:"",brand:"DJI",category:"Camera Drone",sku:"",price:0,oldPrice:0,stock:0,reorderLevel:5,unitCost:0,warehouse:"Dhaka Main Warehouse",supplier:"",images:[],image:"",status:"published",badge:"",youtubeUrl:"",description:"",descriptionHtml:starterHtml,descriptionCss:starterCss,preorderEnabled:true,preorderDepositPercent:30,preorderNote:"Reserve this product before the next shipment arrives.",keyFeaturesText:"",specificationsText:"",isFeatured:false,isNewArrival:false,isPopular:false,isActive:true,dronesMenuGroup:"",dronesMenuOrder:0,handheldsMenuGroup:"",handheldsMenuOrder:0,enterpriseMenuGroup:"",enterpriseMenuOrder:0 };
const productKey="drone-admin-products";

function mapSpecifications(value: unknown): Record<string,string> {
  if (!value) return {};
  if (value instanceof Map) return Object.fromEntries([...value.entries()].map(([k,v])=>[String(k),String(v)]));
  if (typeof value === "object" && !Array.isArray(value)) return Object.fromEntries(Object.entries(value as Record<string,unknown>).map(([k,v])=>[k,String(v)]));
  return {};
}
function normalizeProduct(value: Partial<AdminProduct> & { _id?: string; shortDescription?: string }, index=0): AdminProduct {
  const images=Array.isArray(value.images)?value.images.filter(Boolean):value.image?[value.image]:[];
  const menuPlacements = Array.isArray(value.menuPlacements) ? value.menuPlacements.filter((item): item is MenuPlacement => Boolean(item && typeof item === "object" && ["drones","handhelds","enterprise"].includes(String((item as MenuPlacement).menu)) && String((item as MenuPlacement).group || "").trim())).map((item) => ({ menu:item.menu, group:String(item.group).trim(), sortOrder:Number(item.sortOrder||0), isActive:item.isActive!==false })) : [];
  return { ...starterProduct, ...value, id:value.id||value._id||`managed-${index}`, images, image:value.image||images[0]||"", brand:value.brand||"DJI", sku:value.sku||"", description:value.description||value.shortDescription||"", price:Number(value.price||0),oldPrice:Number(value.oldPrice||value.price||0),stock:Number(value.stock||0),reorderLevel:Number(value.reorderLevel||5),unitCost:Number(value.unitCost||0),warehouse:value.warehouse||"Dhaka Main Warehouse",supplier:value.supplier||"",descriptionHtml:value.descriptionHtml||(value.description?`<p>${value.description}</p>`:starterHtml),descriptionCss:value.descriptionCss||starterCss,preorderEnabled:value.preorderEnabled!==false,preorderDepositPercent:Number(value.preorderDepositPercent||30),preorderNote:value.preorderNote||starterProduct.preorderNote,keyFeatures:Array.isArray(value.keyFeatures)?value.keyFeatures.map(String):[],specifications:mapSpecifications(value.specifications),isFeatured:Boolean(value.isFeatured),isNewArrival:Boolean(value.isNewArrival),isPopular:Boolean(value.isPopular),isActive:value.isActive!==false,status:(value.status as ProductStatus)||"published",badge:value.badge||"",youtubeUrl:value.youtubeUrl||"",menuPlacements };
}
function toForm(product:AdminProduct):ProductForm {
  const placement=(menu:MenuPlacement["menu"])=>product.menuPlacements.find(item=>item.menu===menu);
  return { ...product, keyFeaturesText:product.keyFeatures.join("\n"), specificationsText:Object.entries(product.specifications).map(([k,v])=>`${k}: ${v}`).join("\n"), dronesMenuGroup:placement("drones")?.group||"",dronesMenuOrder:placement("drones")?.sortOrder||0,handheldsMenuGroup:placement("handhelds")?.group||"",handheldsMenuOrder:placement("handhelds")?.sortOrder||0,enterpriseMenuGroup:placement("enterprise")?.group||"",enterpriseMenuOrder:placement("enterprise")?.sortOrder||0 };
}
function parseSpecs(value:string){return Object.fromEntries(value.split("\n").map(line=>line.trim()).filter(Boolean).map(line=>{const [key,...rest]=line.split(":");return [key.trim(),rest.join(":").trim()] as const}).filter(([k,v])=>k&&v));}
function slugify(value:string){return value.toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"");}

export default function AdminProducts(){
  const searchParams=useSearchParams(); const importRef=useRef<HTMLInputElement|null>(null);
  const [products,setProducts]=useState<AdminProduct[]>(getApiBase()?[]:[starterProduct]); const [form,setForm]=useState<ProductForm>(blank); const [editing,setEditing]=useState<string|null>(null); const [search,setSearch]=useState(searchParams.get("q")||""); const [categoryFilter,setCategoryFilter]=useState(""); const [brandFilter,setBrandFilter]=useState(""); const [statusFilter,setStatusFilter]=useState(""); const [notice,setNotice]=useState(""); const [categories,setCategories]=useState<string[]>(["Camera Drone","Handhelds","Accessories","Combo"]); const [brands,setBrands]=useState<string[]>(["DJI","DJI Enterprise"]);
  useEffect(()=>{const load=async()=>{try{if(getApiBase()){const [p,c,b]=await Promise.all([apiRequest<{data?:unknown}>("/admin/products?limit=100"),apiRequest<{data?:ContentOption[]}>("/admin/categories").catch(()=>({data:[]})),apiRequest<{data?:ContentOption[]}>("/admin/brands").catch(()=>({data:[]}))]);if(Array.isArray(p.data))setProducts(p.data.map((item,index)=>normalizeProduct(item as Partial<AdminProduct>&{_id?:string},index)));const cs=(c.data||[]).map(x=>x.title||x.name).filter(Boolean) as string[];const bs=(b.data||[]).map(x=>x.title||x.name).filter(Boolean) as string[];if(cs.length)setCategories(cs);setBrands([...new Set(["DJI","DJI Enterprise",...bs])]);return;}const stored=localStorage.getItem(productKey);if(stored)setProducts((JSON.parse(stored) as Partial<AdminProduct>[]).map(normalizeProduct));}catch(e){setNotice(e instanceof Error?e.message:"Unable to load products")}};void load()},[]);
  useEffect(()=>{if(searchParams.get("new")==="1"){setEditing(null);setForm(blank);window.scrollTo({top:0,behavior:"smooth"});}},[searchParams]);
  const visible=useMemo(()=>products.filter(p=>`${p.name} ${p.category} ${p.brand} ${p.sku} ${p.slug}`.toLowerCase().includes(search.toLowerCase())&&(!categoryFilter||p.category===categoryFilter)&&(!brandFilter||p.brand===brandFilter)&&(!statusFilter||p.status===statusFilter)),[products,search,categoryFilter,brandFilter,statusFilter]);
  function persist(next:AdminProduct[]){setProducts(next);localStorage.setItem(productKey,JSON.stringify(next));window.dispatchEvent(new Event("drone-products-updated"));}
  async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setNotice("");const menuPlacements:MenuPlacement[]=[
      form.dronesMenuGroup.trim()?{menu:"drones",group:form.dronesMenuGroup.trim(),sortOrder:Number(form.dronesMenuOrder||0),isActive:true}:null,
      form.handheldsMenuGroup.trim()?{menu:"handhelds",group:form.handheldsMenuGroup.trim(),sortOrder:Number(form.handheldsMenuOrder||0),isActive:true}:null,
      form.enterpriseMenuGroup.trim()?{menu:"enterprise",group:form.enterpriseMenuGroup.trim(),sortOrder:Number(form.enterpriseMenuOrder||0),isActive:true}:null,
    ].filter((item): item is MenuPlacement => Boolean(item));
    const payload={name:form.name,slug:form.slug||slugify(form.name),brand:form.brand,category:form.category,sku:form.sku,price:form.price,oldPrice:form.oldPrice||form.price,stock:form.stock,preorderEnabled:form.preorderEnabled,preorderDepositPercent:form.preorderDepositPercent,preorderNote:form.preorderNote,reorderLevel:form.reorderLevel,unitCost:form.unitCost,warehouse:form.warehouse,supplier:form.supplier,images:form.images.length?form.images:(form.image?[form.image]:[]),youtubeUrl:form.youtubeUrl,shortDescription:form.description,descriptionHtml:form.descriptionHtml,descriptionCss:form.descriptionCss,keyFeatures:form.keyFeaturesText.split("\n").map(x=>x.trim()).filter(Boolean),specifications:parseSpecs(form.specificationsText),badge:form.badge,status:form.status,isFeatured:form.isFeatured,isNewArrival:form.isNewArrival,isPopular:form.isPopular,isActive:form.isActive,menuPlacements};try{if(getApiBase()){const response=await apiRequest<{data?:unknown}>(editing?`/admin/products/${editing}`:"/admin/products",{method:editing?"PATCH":"POST",body:JSON.stringify(payload)});const saved=normalizeProduct(response.data as Partial<AdminProduct>&{_id?:string},products.length);setProducts(current=>editing?current.map(item=>item.id===editing?saved:item):[saved,...current]);}else{const saved=normalizeProduct({...payload,id:editing||crypto.randomUUID()},products.length);persist(editing?products.map(item=>item.id===editing?saved:item):[saved,...products]);}setNotice(editing?"Product updated":"Product created");setEditing(null);setForm(blank);}catch(e){setNotice(e instanceof Error?e.message:"Unable to save product")}setTimeout(()=>setNotice(""),2500)}
  function edit(product:AdminProduct){setForm(toForm(product));setEditing(product.id);window.scrollTo({top:0,behavior:"smooth"})}
  async function remove(id:string){if(!confirm("Delete this product?"))return;try{if(getApiBase())await apiRequest(`/admin/products/${id}`,{method:"DELETE"});const next=products.filter(p=>p.id!==id);if(getApiBase())setProducts(next);else persist(next);setNotice("Product deleted")}catch(e){setNotice(e instanceof Error?e.message:"Unable to delete product")}}
  async function readImage(file?:File){if(!file)return;try{let url="";if(getApiBase()){const data=new FormData();data.append("image",file);const response=await apiFormRequest<{data?:{url?:string}}>("/admin/media?folder=products",data);url=response.data?.url||"";}else{url=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=()=>reject(reader.error);reader.readAsDataURL(file)})}if(url)setForm(current=>({...current,images:[...current.images,url],image:current.image||url}))}catch(e){setNotice(e instanceof Error?e.message:"Image upload failed")}}
  function removeImage(url:string){setForm(current=>{const images=current.images.filter(x=>x!==url);return {...current,images,image:current.image===url?(images[0]||""):current.image}})}
  function exportCsv(){const headers=["name","slug","brand","category","sku","price","oldPrice","stock","reorderLevel","unitCost","warehouse","supplier","status","isFeatured","isNewArrival","isPopular","isActive"];const esc=(v:unknown)=>`"${String(v??"").replaceAll('"','""')}"`;const csv=[headers.join(","),...products.map(p=>headers.map(h=>esc((p as unknown as Record<string,unknown>)[h])).join(","))].join("\n");const blob=new Blob([csv],{type:"text/csv;charset=utf-8"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`drone-bangladesh-products-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(url)}
  async function importCsv(file?:File){if(!file)return;try{const text=await file.text();const lines=text.split(/\r?\n/).filter(Boolean);if(lines.length<2)throw new Error("CSV file has no product rows");const parse=(line:string)=>{const out:string[]=[];let cur="",quoted=false;for(let i=0;i<line.length;i++){const ch=line[i];if(ch==='"'){if(quoted&&line[i+1]==='"'){cur+='"';i++}else quoted=!quoted}else if(ch===","&&!quoted){out.push(cur);cur=""}else cur+=ch}out.push(cur);return out};const headers=parse(lines[0]);let created=0;for(const line of lines.slice(1)){const values=parse(line);const row=Object.fromEntries(headers.map((h,i)=>[h,values[i]??""])) as Record<string,string>;if(!row.name)continue;const payload={...row,price:Number(row.price||0),oldPrice:Number(row.oldPrice||0),stock:Number(row.stock||0),reorderLevel:Number(row.reorderLevel||5),unitCost:Number(row.unitCost||0),isFeatured:row.isFeatured==="true",isNewArrival:row.isNewArrival==="true",isPopular:row.isPopular==="true",isActive:row.isActive!=="false",slug:row.slug||slugify(row.name),images:[]};if(getApiBase())await apiRequest("/admin/products",{method:"POST",body:JSON.stringify(payload)});created++}setNotice(`${created} products imported`);window.location.reload()}catch(e){setNotice(e instanceof Error?e.message:"Import failed")}}
  return <section className="admin-crud admin-products-page"><div className="admin-crud-heading"><div><p className="eyebrow">CATALOG MANAGEMENT</p><h1>Products Management</h1><span>Manage product data, stock, gallery, features, specifications and storefront flags.</span></div><div className="admin-heading-actions"><button type="button" className="admin-inline-link" onClick={exportCsv}><Download size={15}/> Export</button><button type="button" className="admin-inline-link" onClick={()=>importRef.current?.click()}><Upload size={15}/> Import</button><input ref={importRef} hidden type="file" accept=".csv,text/csv" onChange={e=>void importCsv(e.target.files?.[0])}/><Link className="admin-inline-link" href="/admin/buy-combo"><Link2 size={15}/> Buy Combo manager</Link><div className="crud-summary"><strong>{products.length}</strong><small>Total products</small></div></div></div>{notice&&<div className="crud-notice">{notice}</div>}
    <div className="admin-product-stat-grid"><div><strong>{products.length}</strong><span>Total products</span></div><div><strong>{products.filter(x=>x.status==="published").length}</strong><span>Published</span></div><div><strong>{products.filter(x=>x.stock<10).length}</strong><span>Low stock</span></div><div><strong>{products.filter(x=>x.isNewArrival).length}</strong><span>New arrivals</span></div></div>
    <div className="crud-grid"><form className="crud-form product-editor-form" onSubmit={submit}><div className="admin-panel-heading"><h2>{editing?"Edit product":"Add product"}</h2>{editing&&<button type="button" className="icon-button" onClick={()=>{setEditing(null);setForm(blank)}}><X size={16}/></button>}</div>
      <label>Product title<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value,slug:form.slug||slugify(e.target.value)})}/></label><label>Slug<input required value={form.slug} onChange={e=>setForm({...form,slug:e.target.value})}/></label>
      <div className="form-grid"><label>Brand<select value={form.brand} onChange={e=>setForm({...form,brand:e.target.value})}><option value="">Select Brand</option>{brands.map(x=><option key={x} value={x}>{x}</option>)}</select></label><label>Category<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}><option value="">Select Category</option>{categories.map(x=><option key={x} value={x}>{x}</option>)}</select></label></div>
      <div className="form-grid"><label>SKU<input value={form.sku} onChange={e=>setForm({...form,sku:e.target.value})}/></label><label>Badge<input value={form.badge} onChange={e=>setForm({...form,badge:e.target.value})} placeholder="HOT / BEST SELLER"/></label></div>
      <div className="form-grid"><label>Sale price (৳)<input type="number" min="0" required value={form.price} onChange={e=>setForm({...form,price:Number(e.target.value)})}/></label><label>Regular price (৳)<input type="number" min="0" value={form.oldPrice} onChange={e=>setForm({...form,oldPrice:Number(e.target.value)})}/></label></div><div className="form-grid"><label>Stock<input type="number" min="0" required value={form.stock} onChange={e=>setForm({...form,stock:Number(e.target.value)})}/></label><label>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value as ProductStatus})}><option value="published">Published</option><option value="draft">Draft</option><option value="archived">Archived</option></select></label></div><div className="form-grid"><label>Reorder level<input type="number" min="0" value={form.reorderLevel} onChange={e=>setForm({...form,reorderLevel:Number(e.target.value)})}/></label><label>Unit cost (৳)<input type="number" min="0" value={form.unitCost} onChange={e=>setForm({...form,unitCost:Number(e.target.value)})}/></label></div><div className="form-grid"><label>Warehouse<input value={form.warehouse} onChange={e=>setForm({...form,warehouse:e.target.value})}/></label><label>Supplier<input value={form.supplier} onChange={e=>setForm({...form,supplier:e.target.value})}/></label></div>
      <label>Gallery images<input type="file" accept="image/*" multiple onChange={e=>Array.from(e.target.files||[]).forEach(file=>void readImage(file))}/><small className="file-hint"><ImagePlus size={14}/>Upload one or more product images</small></label>{form.images.length>0&&<div className="admin-gallery-preview">{form.images.map(url=><div key={url}><img src={url} alt="Product"/><button type="button" onClick={()=>removeImage(url)}>×</button></div>)}</div>}
      <label>YouTube URL<input value={form.youtubeUrl} onChange={e=>setForm({...form,youtubeUrl:e.target.value})} placeholder="https://youtube.com/..."/></label><label>Plain-text summary<textarea rows={3} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label>Key features (one per line)<textarea rows={5} value={form.keyFeaturesText} onChange={e=>setForm({...form,keyFeaturesText:e.target.value})}/></label><label>Specifications (one per line: Key: Value)<textarea rows={7} value={form.specificationsText} onChange={e=>setForm({...form,specificationsText:e.target.value})} placeholder={'Camera: 1-inch CMOS\nFlight Time: 52 minutes'}/></label>
      <div className="admin-special-fields preorder-settings"><h3>Pre-order settings</h3><p className="admin-field-help">Enable advance bookings for stock-out or upcoming products. Customers can choose full or partial payment.</p><div className="admin-special-grid"><label className="file-hint"><input type="checkbox" checked={form.preorderEnabled} onChange={e=>setForm({...form,preorderEnabled:e.target.checked})}/> Allow Pre-Order</label><label>Deposit percentage<input type="number" min="1" max="100" value={form.preorderDepositPercent} onChange={e=>setForm({...form,preorderDepositPercent:Number(e.target.value)})}/></label><label>Customer message<input value={form.preorderNote} onChange={e=>setForm({...form,preorderNote:e.target.value})} placeholder="Reserve before the next shipment"/></label></div></div><div className="admin-checkbox-grid"><label><input type="checkbox" checked={form.isFeatured} onChange={e=>setForm({...form,isFeatured:e.target.checked})}/> Featured</label><label><input type="checkbox" checked={form.isNewArrival} onChange={e=>setForm({...form,isNewArrival:e.target.checked})}/> New Arrival</label><label><input type="checkbox" checked={form.isPopular} onChange={e=>setForm({...form,isPopular:e.target.checked})}/> Popular</label><label><input type="checkbox" checked={form.isActive} onChange={e=>setForm({...form,isActive:e.target.checked})}/> Active</label></div>
      <div className="admin-special-fields product-menu-placement"><h3>Navigation mega-menu placement</h3><p className="admin-field-help">Type a group name to publish this product inside that menu. Leave a group blank to keep the product out of that menu.</p><div className="product-menu-placement-grid"><div><strong>Drones</strong><label>Group / column<input value={form.dronesMenuGroup} onChange={e=>setForm({...form,dronesMenuGroup:e.target.value})} placeholder="DJI Mini"/></label><label>Menu order<input type="number" value={form.dronesMenuOrder} onChange={e=>setForm({...form,dronesMenuOrder:Number(e.target.value)})}/></label></div><div><strong>Handhelds</strong><label>Group / column<input value={form.handheldsMenuGroup} onChange={e=>setForm({...form,handheldsMenuGroup:e.target.value})} placeholder="DJI Osmo Series"/></label><label>Menu order<input type="number" value={form.handheldsMenuOrder} onChange={e=>setForm({...form,handheldsMenuOrder:Number(e.target.value)})}/></label></div><div><strong>Enterprise &amp; Agriculture</strong><label>Group / column<input value={form.enterpriseMenuGroup} onChange={e=>setForm({...form,enterpriseMenuGroup:e.target.value})} placeholder="AGRAS"/></label><label>Menu order<input type="number" value={form.enterpriseMenuOrder} onChange={e=>setForm({...form,enterpriseMenuOrder:Number(e.target.value)})}/></label></div></div></div>
      <RichDescriptionEditor value={{html:form.descriptionHtml,css:form.descriptionCss}} onChange={d=>setForm({...form,descriptionHtml:d.html,descriptionCss:d.css})}/><Link className="admin-inline-link product-combo-link" href={`/admin/buy-combo?product=${encodeURIComponent(form.slug)}`}><Link2 size={15}/> Configure Buy Combo / accessories</Link><button className="button button-red" type="submit">{editing?<><Save size={15}/>Save product</>:<><Plus size={15}/>Create product</>}</button></form>
      <section className="crud-list"><div className="crud-list-toolbar product-filter-toolbar"><div><h2>Catalog</h2><span>{visible.length} products shown</span></div><label className="crud-search"><Search size={15}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search product, SKU, category or brand"/></label><select value={categoryFilter} onChange={e=>setCategoryFilter(e.target.value)}><option value="">All categories</option>{categories.map(x=><option key={x}>{x}</option>)}</select><select value={brandFilter} onChange={e=>setBrandFilter(e.target.value)}><option value="">All brands</option>{brands.map(x=><option key={x}>{x}</option>)}</select><select value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="">All status</option><option value="published">Published</option><option value="draft">Draft</option><option value="archived">Archived</option></select><button className="text-button" onClick={()=>{setSearch("");setCategoryFilter("");setBrandFilter("");setStatusFilter("")}}>Reset</button></div><div className="crud-table">{visible.map(product=><article className="crud-row product-admin-row" key={product.id}><img src={product.image||"/images/products/mini-5.jpg"} alt=""/><div className="crud-product-name"><strong>{product.name}</strong><small>{product.brand} · {product.category} · {product.sku||product.slug}</small></div><span className="crud-price">৳{product.price.toLocaleString("en-BD")}</span><span className={`crud-status ${product.status}`}>{product.status}</span><span className={`crud-stock ${product.stock<10?"is-low":""}`}>{product.stock} in stock</span><div className="crud-actions"><Link className="icon-button" href={`/products/${product.slug}`}>↗</Link><button className="icon-button" onClick={()=>edit(product)}><Pencil size={14}/></button><button className="icon-button danger" onClick={()=>void remove(product.id)}><Trash2 size={14}/></button></div></article>)}{visible.length===0&&<div className="crud-empty">No products match your search.</div>}</div></section></div>
  </section>;
}
