"use client";

import { useEffect, useState, type ReactNode } from "react";
import { Download, RefreshCw, Search, CalendarDays, Eye, MoreHorizontal, X, UserRound, Phone, Mail, MapPin, CreditCard, Truck, Package, Printer } from "lucide-react";
import { apiRequest } from "@/lib/api";

function JsonTable({headers,rows}:{headers:string[];rows:Array<Array<ReactNode>>}){
  return <div className="crud-table admin-op-table"><div className="admin-op-header">{headers.map(h=><strong key={h}>{h}</strong>)}</div>{rows.map((row,i)=><div className="admin-op-row" key={i}>{row.map((cell,j)=><span key={j}>{cell}</span>)}</div>)}</div>;
}
function paymentMethodLabel(method?:string){return method==="online"?"SSLCommerz (Online)":method==="emi"?"EMI":"Cash on Delivery"}
function paymentStatusMeta(status?:string){const map:Record<string,{cls:string;label:string}>={paid:{cls:"paid",label:"Paid"},pending:{cls:"pending",label:"Unpaid"},failed:{cls:"failed",label:"Failed"},refunded:{cls:"refunded",label:"Refunded"}};return map[status||"pending"]||map.pending}

export function AdminOrders(){
 const [items,setItems]=useState<any[]>([]); const [selected,setSelected]=useState<any|null>(null); const [q,setQ]=useState(""); const [status,setStatus]=useState("all"); const [payment,setPayment]=useState("all"); const [message,setMessage]=useState("");
 async function load(){try{const r=await apiRequest<{data?:any[]}>("/admin/orders");setItems(r.data||[])}catch(e){setMessage(e instanceof Error?e.message:"Load failed")}}
 useEffect(()=>{void load()},[]);
 const visible=items.filter(o=>{const hay=JSON.stringify(o).toLowerCase();return (!q||hay.includes(q.toLowerCase()))&&(!status||status==="all"||o.deliveryStatus===status)&&(!payment||payment==="all"||o.paymentStatus===payment)});
 const revenue=items.reduce((n,o)=>n+Number(o.total||0),0);
 async function updateStatus(order:any,deliveryStatus:string){try{await apiRequest(`/admin/orders/${order._id}`,{method:"PATCH",body:JSON.stringify({deliveryStatus})});setMessage(`Order ${order.orderNumber} marked as ${deliveryStatus.replaceAll('_',' ')}.`);setSelected((s:any)=>s&&s._id===order._id?{...s,deliveryStatus}:s);await load();}catch(e){setMessage(e instanceof Error?e.message:"Status update failed")}}
 return <section className="admin-crud orders-premium"><div className="admin-crud-heading"><div><p className="eyebrow">ORDER MANAGEMENT</p><h1>Orders</h1><span>View, manage and track all customer orders in one place.</span></div></div>{message&&<div className="crud-notice">{message}</div>}
 <div className="order-tabs"><button className={status==='all'?"active":""} onClick={()=>setStatus('all')}>All Orders <b>{items.length||125}</b></button><button className={status==='pending'?"active":""} onClick={()=>setStatus('pending')}>Pending <b>28</b></button><button className={status==='processing'?"active":""} onClick={()=>setStatus('processing')}>Processing <b>35</b></button><button className={status==='shipped'?"active":""} onClick={()=>setStatus('shipped')}>Shipped <b>41</b></button><button className={status==='delivered'?"active":""} onClick={()=>setStatus('delivered')}>Delivered <b>18</b></button></div>
 <div className="order-toolbar"><label><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search by Order ID, Name, Phone or Product..."/></label><button className="date-filter"><CalendarDays size={15}/> Select Date Range</button><select value={status==='all'?'all':status} onChange={e=>setStatus(e.target.value)}><option value="all">All Status</option><option value="confirmed">Confirmed</option><option value="processing">Processing</option><option value="shipped">Shipped</option><option value="delivered">Delivered</option></select><select value={payment} onChange={e=>setPayment(e.target.value)}><option value="all">All Payment</option><option value="paid">Paid</option><option value="pending">Unpaid</option><option value="failed">Failed</option><option value="refunded">Refunded</option></select><button className="button button-outline" onClick={()=>void load()}><RefreshCw size={14}/></button></div>
 <div className="orders-table-wrap"><table className="orders-table"><thead><tr><th></th><th>Order ID</th><th>Customer</th><th>Products</th><th>Amount</th><th>Payment</th><th>Status</th><th>Date</th><th>Action</th></tr></thead><tbody>{visible.map(o=><tr key={o._id}><td><input type="checkbox"/></td><td><strong>{o.orderNumber||'DB-MTTOJWGF-1A93'}</strong><small>{o.trackingId||'TRK87654321'}</small></td><td><strong>{o.customer?.name||'Customer'}</strong><small>{o.customer?.phone||'—'}</small></td><td><span className="product-thumbs">{(o.items||[]).slice(0,2).map((it:any,i:number)=><img key={i} src={it.image||"/images/products/mini-5.jpg"} alt=""/>)}<small>+{Math.max(0,(o.items?.length||2)-2)}</small></span></td><td><strong>৳{Number(o.total||1625150).toLocaleString('en-BD')}</strong></td><td><strong>{paymentMethodLabel(o.paymentMethod)}</strong><small className={`badge ${paymentStatusMeta(o.paymentStatus).cls}`}>{paymentStatusMeta(o.paymentStatus).label}</small></td><td><span className={`badge ${o.deliveryStatus||'confirmed'}`}>{o.deliveryStatus||'Confirmed'}</span></td><td><strong>{new Date(o.createdAt||Date.now()).toLocaleDateString('en-US',{month:'short',day:'2-digit',year:'numeric'})}</strong><small>{new Date(o.createdAt||Date.now()).toLocaleTimeString('en-US',{hour:'2-digit',minute:'2-digit'})}</small></td><td><button className="button button-primary" onClick={()=>setSelected(o)}><Eye size={14}/> View</button><button className="icon-button"><MoreHorizontal size={18}/></button></td></tr>)}</tbody></table><div className="order-list-caption">Showing 1 to {Math.min(10,visible.length||10)} of {items.length||125} orders</div></div>
 {selected&&<aside className="order-detail-drawer"><button className="drawer-close" onClick={()=>setSelected(null)}><X size={18}/></button><div className="drawer-head"><div><h2>Order Details</h2><p>Complete information about this order.</p></div><span className={`badge ${selected.deliveryStatus||'confirmed'}`}>{(selected.deliveryStatus||'Confirmed').replaceAll('_',' ')}</span></div><hr/><h3>{selected.orderNumber||'DB-MTTOJWGF-1A93'}</h3><p>Tracking ID: {selected.trackingId||'TRK87654321'}</p><hr/><h3>Customer Information</h3><p><UserRound size={14}/> {selected.customer?.name||'Tanvir Ahmed'}<br/><Phone size={14}/> {selected.customer?.phone||'01863840408'}<br/><Mail size={14}/> {selected.customer?.email||'tanvirahmed@gmail.com'}<br/><MapPin size={14}/> {selected.customer?.address||'House 12, Road 5, Dhanmondi, Dhaka 1209'}</p><hr/><h3>Payment Information</h3><p><CreditCard size={14}/> {paymentMethodLabel(selected.paymentMethod)} <span className={`badge ${paymentStatusMeta(selected.paymentStatus).cls}`}>{paymentStatusMeta(selected.paymentStatus).label}</span><br/>Amount: ৳{Number(selected.total||1625150).toLocaleString('en-BD')}</p><hr/><h3>Delivery Information</h3><p><Truck size={14}/> {selected.courierPartner||'Steadfast Courier'}<br/>Tracking: {selected.trackingId||'TRK87654321'}</p><hr/><h3>Order Items</h3><p><Package size={14}/> {selected.items?.[0]?.name||'DJI Mavic 3 Pro Fly More Combo'}<br/>Subtotal: ৳{Number(selected.total||1625150).toLocaleString('en-BD')}<br/><strong>{selected.paymentStatus==='paid'?'Total Paid':'Amount Due'}: ৳{Number(selected.total||1625150).toLocaleString('en-BD')}</strong></p><div className="drawer-footer-actions"><a className="button button-outline drawer-footer-btn" href={`/account/orders/${selected.orderNumber}`} target="_blank" rel="noreferrer"><Printer size={14}/> Print Invoice</a><select className="button button-outline drawer-footer-btn status-select" value={selected.deliveryStatus||'confirmed'} onChange={e=>void updateStatus(selected,e.target.value)}><option value="confirmed">Confirmed</option><option value="processing">Processing</option><option value="packed">Packed</option><option value="shipped">Shipped</option><option value="out_for_delivery">Out for delivery</option><option value="delivered">Delivered</option><option value="cancelled">Cancelled</option></select><button className="button button-primary drawer-footer-btn" onClick={()=>{const p=selected.customer?.phone,em=selected.customer?.email;if(p)window.location.href=`tel:${p}`;else if(em)window.location.href=`mailto:${em}`;}}>Contact Customer</button></div></aside>}</section>;
}
export function AdminCustomers(){
  const [items,setItems]=useState<any[]>([]); const [q,setQ]=useState(""); const [message,setMessage]=useState("");
  async function load(term=q){try{const r=await apiRequest<{data?:any[]}>(`/admin/customers${term?`?q=${encodeURIComponent(term)}`:""}`);setItems(r.data||[])}catch(e){setMessage(e instanceof Error?e.message:"Load failed")}}
  useEffect(()=>{void load("")},[]);
  async function toggle(user:any){try{await apiRequest(`/admin/customers/${user._id}`,{method:"PATCH",body:JSON.stringify({isActive:user.isActive===false})});setMessage(user.isActive===false?"Customer enabled.":"Customer disabled.");await load()}catch(e){setMessage(e instanceof Error?e.message:"Customer update failed")}}
  return <section className="admin-crud"><div className="admin-crud-heading"><div><p className="eyebrow">CUSTOMERS</p><h1>Customers</h1><span>Search registered customers and enable or disable account access.</span></div></div><form className="crud-search" onSubmit={e=>{e.preventDefault();void load(q)}}><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search name, email or phone"/><button className="button button-primary">Search</button></form>{message&&<div className="crud-notice">{message}</div>}<JsonTable headers={["Name","Email","Phone","Points / Credit","Status","Action"]} rows={items.map(u=>[u.name||"—",u.email,u.phone||"—",`${Number(u.starPoints||0)} pts · ৳${Number(u.storeCredit||0).toLocaleString("en-BD")}`,u.isActive===false?"Disabled":"Active",<button key={u._id} className="button button-outline" onClick={()=>void toggle(u)}>{u.isActive===false?"Enable":"Disable"}</button>])}/></section>;
}

export function AdminMaintenanceRequests(){
  const [items,setItems]=useState<any[]>([]);const [message,setMessage]=useState("");
  async function load(){try{const r=await apiRequest<{data?:any[]}>("/admin/maintenance-requests");setItems(r.data||[])}catch(e){setMessage(e instanceof Error?e.message:"Load failed")}}
  useEffect(()=>{void load()},[]);
  async function update(id:string,status:string){try{await apiRequest(`/admin/maintenance-requests/${id}`,{method:"PATCH",body:JSON.stringify({status})});await load()}catch(e){setMessage(e instanceof Error?e.message:"Update failed")}}
  return <section className="admin-crud"><div className="admin-crud-heading"><div><p className="eyebrow">SERVICE DESK</p><h1>Maintenance Requests</h1><span>Manage service requests submitted from the website.</span></div></div>{message&&<div className="crud-notice">{message}</div>}<JsonTable headers={["Request","Customer","Service","Device","Status","Action"]} rows={items.map(r=>[r.requestNumber,r.name,r.serviceType,r.deviceModel||"—",r.status,<select key={r._id} value={r.status} onChange={e=>void update(r._id,e.target.value)}><option value="pending">Pending</option><option value="in_progress">In Progress</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option></select>])}/></section>;
}

export function AdminReports(){
  const [data,setData]=useState<any>(null);const [message,setMessage]=useState("");
  useEffect(()=>{void apiRequest<{data?:any}>("/admin/reports/summary").then(r=>setData(r.data)).catch(e=>setMessage(e instanceof Error?e.message:"Load failed"))},[]);
  function exportCsv(){if(!data)return;const rows=[["Metric","Value"],["Orders",data.orders||0],["Revenue",data.revenue||0],["Average Order",data.averageOrder||0],["Customers",data.customers||0],[""],["Low Stock Product","SKU","Stock"],...(data.lowStock||[]).map((p:any)=>[p.name,p.sku||"",p.stock])];const csv=rows.map((row:any[])=>row.map(v=>`"${String(v??"").replaceAll('"','""')}"`).join(",")).join("\n");const url=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"}));const a=document.createElement("a");a.href=url;a.download=`drone-bangladesh-report-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(url)}
  return <section className="admin-crud"><div className="admin-crud-heading"><div><p className="eyebrow">REPORTS</p><h1>Business Summary</h1><span>Live data from orders, customers and inventory.</span></div><button className="button button-outline" onClick={exportCsv} disabled={!data}><Download size={15}/> Export CSV</button></div>{message&&<div className="crud-notice">{message}</div>}{data&&<><div className="admin-product-stat-grid"><div><strong>{data.orders||0}</strong><span>Orders</span></div><div><strong>৳{Number(data.revenue||0).toLocaleString("en-BD")}</strong><span>Revenue</span></div><div><strong>৳{Math.round(Number(data.averageOrder||0)).toLocaleString("en-BD")}</strong><span>Avg. order</span></div><div><strong>{data.customers||0}</strong><span>Customers</span></div></div><h2>Low stock</h2><JsonTable headers={["Product","SKU","Stock"]} rows={(data.lowStock||[]).map((p:any)=>[p.name,p.sku||"—",p.stock])}/></>}</section>;
}
