"use client";

import { RefreshCw } from "lucide-react";
import { useEffect, useState } from "react";
import { apiRequest } from "@/lib/api";

type PreOrder = { _id: string; preOrderNumber: string; productName: string; quantity: number; customer?: { name?: string; email?: string; phone?: string }; subtotal?: number; amountDue?: number; remainingAmount?: number; paymentPlan?: string; paymentStatus?: string; status?: string; createdAt?: string };
const money = (value: unknown) => `৳${Number(value || 0).toLocaleString("en-BD")}`;

export default function AdminPreorders() {
  const [items, setItems] = useState<PreOrder[]>([]); const [status, setStatus] = useState(""); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  async function load() { setBusy(true); try { const query = status ? `?status=${encodeURIComponent(status)}` : ""; const result = await apiRequest<{ data?: PreOrder[] }>(`/admin/preorders${query}`); setItems(result.data || []); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to load pre-orders"); } finally { setBusy(false); } }
  useEffect(() => { void load(); }, [status]);
  async function update(id: string, changes: Record<string, unknown>) { try { const result = await apiRequest<{ data?: PreOrder }>(`/admin/preorders/${id}`, { method: "PATCH", body: JSON.stringify(changes) }); if (result.data) setItems((current) => current.map((item) => item._id === id ? result.data! : item)); setMessage("Pre-order updated"); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to update pre-order"); } }
  return <section className="admin-crud preorders-admin"><div className="admin-crud-heading"><div><p className="eyebrow">ADVANCE BOOKINGS</p><h1>Pre-Order Management</h1><span>Review stock-out and upcoming product reservations, payment plans and customer details.</span></div><button type="button" className="button button-outline" onClick={() => void load()} disabled={busy}><RefreshCw size={14}/> Refresh</button></div>{message && <div className="crud-notice">{message}</div>}<div className="preorder-toolbar"><strong>{items.length} booking{items.length === 1 ? "" : "s"}</strong><select value={status} onChange={(event) => setStatus(event.target.value)}><option value="">All status</option><option value="pending">Pending</option><option value="confirmed">Confirmed</option><option value="ready">Ready / Restocked</option><option value="fulfilled">Fulfilled</option><option value="cancelled">Cancelled</option></select></div><div className="preorder-table"><div className="preorder-table-head"><span>Booking / Product</span><span>Customer</span><span>Payment</span><span>Status</span><span>Created</span><span>Action</span></div>{items.map((item) => <article className="preorder-row" key={item._id}><div><strong>{item.preOrderNumber}</strong><small>{item.productName} × {item.quantity}</small></div><div><strong>{item.customer?.name || "—"}</strong><small>{item.customer?.email}<br/>{item.customer?.phone}</small></div><div><strong>{item.paymentPlan === "partial" ? "Partial" : "Full"}</strong><small>Due {money(item.amountDue)} · Balance {money(item.remainingAmount)}</small><select value={item.paymentStatus || "pending"} onChange={(event) => void update(item._id, { paymentStatus: event.target.value })}><option value="pending">Payment pending</option><option value="partial">Partially paid</option><option value="paid">Paid</option><option value="failed">Failed</option><option value="refunded">Refunded</option></select></div><select value={item.status || "pending"} onChange={(event) => void update(item._id, { status: event.target.value })}><option value="pending">Pending</option><option value="confirmed">Confirmed</option><option value="ready">Ready</option><option value="fulfilled">Fulfilled</option><option value="cancelled">Cancelled</option></select><span>{item.createdAt ? new Date(item.createdAt).toLocaleString() : "—"}</span><button type="button" className="text-button" onClick={() => void update(item._id, { status: "confirmed" })}>Confirm</button></article>)}{!items.length && <div className="crud-empty">No pre-orders yet.</div>}</div></section>;
}
