import { Router } from "express";
import { healthRouter } from "../modules/health/health.routes.js";
import { productRouter } from "../modules/products/product.routes.js";
import { authRouter } from "../modules/auth/auth.routes.js";
import { adminRouter } from "../modules/admin/admin.routes.js";
import { mediaRouter } from "../modules/media/media.routes.js";
import { contentRouter } from "../modules/content/content.routes.js";
import { cartRouter } from "../modules/cart/cart.routes.js";
import { orderRouter } from "../modules/orders/order.routes.js";
import { contactRouter } from "../modules/contact/contact.routes.js";
import { maintenanceRequestRouter } from "../modules/maintenance/maintenance-request.routes.js";
import { aiRouter } from "../modules/ai/ai.routes.js";
import { accountRouter } from "../modules/account/account.routes.js";
import { queryRouter } from "../modules/queries/query.routes.js";
import { returnRouter } from "../modules/returns/return.routes.js";
import { reviewRouter } from "../modules/reviews/review.routes.js";
import { preorderRouter } from "../modules/preorders/preorder.routes.js";
import { warrantyRouter } from "../modules/warranty/warranty.routes.js";

export const apiRouter = Router();
apiRouter.use("/health", healthRouter);
apiRouter.use("/products", productRouter);
apiRouter.use("/content", contentRouter);
apiRouter.use("/auth", authRouter);
apiRouter.use("/account", accountRouter);
apiRouter.use("/cart", cartRouter);
apiRouter.use("/orders", orderRouter);
apiRouter.use("/queries", queryRouter);
apiRouter.use("/returns", returnRouter);
apiRouter.use("/reviews", reviewRouter);
apiRouter.use("/preorders", preorderRouter);
apiRouter.use("/warranty", warrantyRouter);
apiRouter.use("/contact", contactRouter);
apiRouter.use("/maintenance-requests", maintenanceRequestRouter);
apiRouter.use("/ai", aiRouter);
apiRouter.use("/admin/media", mediaRouter);
apiRouter.use("/admin", adminRouter);
